// lib/models/todo.dart

// This class represents a single Todo item, mirroring the structure
// of your Todo.java model in the Spring Boot backend.
class Todo {
  final int? id; // Nullable because ID is generated by the backend
  final String description;
  bool completed;

  // Constructor for creating new Todo objects
  Todo({this.id, required this.description, this.completed = false});

  // Factory constructor to create a Todo object from a JSON map (from the backend)
  factory Todo.fromJson(Map<String, dynamic> json) {
    return Todo(
      id: json['id'] as int?, // Cast to int?
      description: json['description'] as String,
      completed: json['completed'] as bool,
    );
  }

  // Method to convert a Todo object to a JSON map (to send to the backend)
  Map<String, dynamic> toJson() {
    return {
      'id': id, // Include ID for updates, null for new creations
      'description': description,
      'completed': completed,
    };
  }

  // Optional: For easier debugging/printing
  @override
  String toString() {
    return 'Todo(id: $id, description: $description, completed: $completed)';
  }
}
